apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-controller-config
  namespace: arenaclients
data:
  config.toml: |-
    VERSION = "2026.01.22-11.13"
    OLD_MATCH_DELETE_AFTER_MINUTES = 10
    JOB_PREFIX= "prod"
    WEBSITE_URL= "https://aiarena.net"
    NAMESPACE= "arenaclients"
    ARENACLIENTS_JSON_PATH = "arenaclients.json"
    INTERVAL_SECONDS = 30
    MAX_ARENACLIENTS = 12
