apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: arenaclients
  name: k8s-controller
  labels:
    app: aiarena-k8s-controller
spec:
  replicas: 1
  selector:	
    matchLabels:	
      app: aiarena-k8s-controller
  template:
    metadata:
      labels:	
        app: aiarena-k8s-controller
    spec:
      containers:
      - image: aiarena/k8s-controller:2026.01.25-16.36
        name: k8s-controller
        ports:
        - containerPort: 8085
          name: 8085tcp
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /health
            port: 8085
            scheme: HTTP
        volumeMounts:
        - mountPath: /app/arenaclients.json
          name: arenaclients-json
          subPath: arenaclients.json
        - mountPath: /app/config.toml
          name: config
          subPath: config.toml
      restartPolicy: Always
      serviceAccount: k8s-controller
      serviceAccountName: k8s-controller
      volumes:
      - name: arenaclients-json
        secret:
          defaultMode: 420
          secretName: arenaclients-secrets
      - name: config
        configMap:
          defaultMode: 420
          name: k8s-controller-config
