ARENA_CLIENT_ID = "aiarenaclient_local"  # ID of arenaclient. Used for AiArena
ROUNDS_PER_RUN = -1  # Set to -1 to ignore this
BASE_WEBSITE_URL = ""
DEBUG_MODE = true  # Enables debug mode for more logging
PYTHON = "python"  # Which python version to use
RUN_TYPE = "local"  # Run on AiArena, locally or test (options: "test", "local", "aiarena")

# LOGGING
LOGGING_LEVEL = "debug" #info,debug,error,trace

# Directories
BOT_DIRECTORY = "/bots"
GAME_DIRECTORY = "/game"

# STARCRAFT
MAX_GAME_TIME = 60486
MAX_REAL_TIME = 7200  # 2 hours in seconds
MAX_FRAME_TIME = 40 # milliseconds
STRIKES = 10
REALTIME = false
VISUALIZE = false

# MATCHES
DISABLE_DEBUG = true
VALIDATE_RACE = false


# Local
MATCHES_FILE=""
RESULTS_FILE=""

AWS = false